name: "Generate Dokka Documentation"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github'
      - 'src'
  push:
    branches:
      - '**'
    paths-ignore:
      - '.idea/**'
      - .gitignore
      - .gitattributes
      - .editorconfig
      - CODEOWNERS
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - SECURITY.md
      - LICENSE
      - README.md

jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dokka Build
        run: './gradlew dokkaGenerate'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          publish_dir: ./build/dokkaHtmlOutput
          publish_branch: gh-pages
          destination_dir: ./